#Modificacion de H2 --- MySQL

spring.datasource.url=jdbc:mysql://localhost:3306/desafio2_db
spring.datasource.username=root
spring.datasource.password=t3l3f0n0

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect